name: Build and test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.1.x"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      # Build the release build
      - name: Build the solution
        run: dotnet build -c Release src/UglyToad.PdfPig.sln

      - name: Run the tests
        run: dotnet test src/UglyToad.PdfPig.sln
